version: '3.2'

services:
    test:
        build: ./web
        restart: always
        environment:
            - APACHE_RUN_USER=www-data
        volumes:
            - ..:/var/www/html
        ports:
            - 8083:80
        working_dir: /var/www/html
        depends_on:
            - test-db

    test-db:
        image: mysql
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: 1
            MYSQL_DATABASE: testdb
        volumes:
            - ../mysql:/var/lib/mysql
        ports:
            - 3306:3306

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
